dbt_deel:
  outputs:
    ci:
      account: ovhzooa-rv77147
      database: dev_deel
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: dbt_ci
      threads: 4
      type: snowflake
      user: VINICIUSNUNEST
      warehouse: case_deel
    prod:
      account: ovhzooa-rv77147
      database: prod_deel
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: dbt
      threads: 4
      type: snowflake
      user: VINICIUSNUNEST
      warehouse: case_deel

