[tool.poetry]
name = "dbt"
version = "0.1.0"
description = ""
authors = ["Vinicius Tavares <vinicius.tavares@q2pay.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
