name: DBT RUN CI - Snowflake
on:
  pull_request:
      types: [opened, reopened, synchronize, ready_for_review]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Node.js for Lightdash CLI
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Install Lightdash CLI
      run: npm install -g @lightdash/cli@latest

    - name: Lightdash CLI deploy
      env:
        DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}
        LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}
        LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}
      run: |
        lightdash dbt run -s payments+ +customers tag:prod --project-dir . --profiles-dir /home/runner/work/case_deel/case_deel --profile dbt_deel --target prod
