name: DBT RUN CI - Snowflake
on:
  pull_request:
      types: [opened, reopened, synchronize, ready_for_review]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dbt
      run: pip install dbt-snowflake

    - name: dbt debug
      env:
        DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      run: dbt debug --profile dbt_deel --target ci

    - name: dbt build
      env:
        DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      run: dbt build --profile dbt_deel --target ci --full-refresh 
    #I didn't configure state:modified and defer because it was a test and I didn't have enough time