name: DBT CI Snowflake
on:
  pull_request:
      types: [opened, reopened, synchronize, ready_for_review]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dbt
      run: pip install dbt-snowflake

    - name: dbt debug
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      run: dbt debug --profile snowflake --target ci

    - name: dbt run
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      run: dbt run --profile snowflake

    - name: dbt test
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      run: dbt test --profile snowflake
